name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'
        
    - name: Display .NET version
      run: dotnet --version
      
    - name: Restore dependencies
      run: dotnet restore ./src/EPaperHatCore/EPaperHatCore.csproj --verbosity minimal
      
    - name: Build
      run: dotnet build ./src/EPaperHatCore/EPaperHatCore.csproj --no-restore
      
    - name: Restore test dependencies
      run: dotnet restore ./tests/EPaperHatCore.Tests/EPaperHatCore.Tests.csproj --verbosity minimal
      
    - name: Test
      run: dotnet test ./tests/EPaperHatCore.Tests/EPaperHatCore.Tests.csproj --no-restore --verbosity normal